# Generated by Django 4.2.13 on 2024-08-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('choice', models.CharField(choices=[('', 'Chosen candidate'), ('Klaus-Werner Iohannis', 'Klaus-Werner Iohannis'), ('Theodor Paleologu', 'Theodor Paleologu'), ('Ilie-Dan Barna', 'Ilie-Dan Barna'), ('Hunor Kelemen', 'Hunor Kelemen'), ('Vasilica-Viorica Dancilă', 'Vasilica-Viorica Dancilă'), ('Cătălin-Sorin Ivan', 'Cătălin-Sorin Ivan'), ('Ninel Peia', 'Ninel Peia'), ('Sebastian-Constantin Popescu', 'Sebastian-Constantin Popescu'), ('John-Ion Banu', 'John-Ion Banu'), ('Mircea Diaconu', 'Mircea Diaconu'), ('Bogdan-Dragoș-Aureliu Marian-Stanoevici', 'Bogdan-Dragoș-Aureliu Marian-Stanoevici'), ('Ramona-Ioana Bruynseels', 'Ramona-Ioana Bruynseels'), ('Viorel Cataramă', 'Viorel Cataramă'), ('Alexandru Cumpănașu', 'Alexandru Cumpănașu')], max_length=100)),
                ('county', models.CharField(choices=[('', 'Select your county'), ('alba', 'Alba'), ('arad', 'Arad'), ('arges', 'Argeș'), ('bacau', 'Bacău'), ('bihor', 'Bihor'), ('bistritanasaud', 'Bistrița-Năsăud'), ('botosani', 'Botoșani'), ('brasov', 'Brașov'), ('braila', 'Brăila'), ('bucuresti', 'București'), ('buzau', 'Buzău'), ('carasseverin', 'Caraș-Severin'), ('cluj', 'Cluj'), ('constanta', 'Constanța'), ('covasna', 'Covasna'), ('calarasi', 'Călărași'), ('dolj', 'Dolj'), ('dambovita', 'Dâmbovița'), ('galati', 'Galați'), ('giurgiu', 'Giurgiu'), ('gorj', 'Gorj'), ('harghita', 'Harghita'), ('hunedoara', 'Hunedoara'), ('ialomita', 'Ialomița'), ('iasi', 'Iași'), ('ilfov', 'Ilfov'), ('maramures', 'Maramureș'), ('mehedinti', 'Mehedinți'), ('mures', 'Mureș'), ('neamt', 'Neamț'), ('olt', 'Olt'), ('prahova', 'Prahova'), ('satumare', 'Satu Mare'), ('sibiu', 'Sibiu'), ('suceava', 'Suceava'), ('salaj', 'Sălaj'), ('teleorman', 'Teleorman'), ('timis', 'Timiș'), ('tulcea', 'Tulcea'), ('vaslui', 'Vaslui'), ('vrancea', 'Vrancea'), ('valcea', 'Vâlcea')], max_length=100)),
            ],
        ),
    ]
